# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.33.3"

default_platform :ios


platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"


    increment_build_number

    # xctool # run the tests of your app
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight do
    carthage
    snapshot
    sigh
    gym(scheme: "Handler") # Build your app - more options available
    pilot
    slack(
      message: "A new TestFlight build was uploaded and be available soon."
    )
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    snapshot
    carthage
    sigh
    gym(scheme: "Handler") # Build your app - more options available
    deliver(force: true)
    slack(
      message: "Successfully deployed new App Update."
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
